### ISSUE TITLE
Nichts funktioniert, alles ist kapput!

### ISSUE THREAD

**Issue by HBTE** [HBTEs/Bla#3]
**Sender**: KMcCxYwhvgw2Y5n6qnMZ@gmx.de

Bitte machen sie alles wieder ganz!

&nbsp;

Viele Gr&uuml;&szlig;e,

Jemand Wichtiges

**Comment by KMcCxYwhvgw2Y5n6qnMZ** [comment]
@HBTE pub
Das muss so sein.

**Comment by HBTE** [comment]
**Sender**: KMcCxYwhvgw2Y5n6qnMZ@gmx.de


Ach so, na dann ist das wohl richtig.


Viele Gr&uuml;&szlig;e,

Jemand Wichtiges
