### ISSUE TITLE
Es funktioniert entlich!

### ISSUE THREAD

**Issue by HBTE** [HBTEs/Bla#52]
**Sender**: Soeiner, Noch <noch.soeiner@gmx.de>

Vielleicht sogar mit Text?

**Comment by KMcCxYwhvgw2Y5n6qnMZ** [comment]
@HBTE pub
Antwort zu trello!

**Comment by KMcCxYwhvgw2Y5n6qnMZ** [comment]
@HBTE pub
 Antwort zu trello!

**Comment by HBTE** [comment]
**Sender**: Soeiner, Noch <noch.soeiner@gmx.de>

Wenn das jetzt noch mit Emails klappt bin ich hyped!
&nbsp;

**Comment by KMcCxYwhvgw2Y5n6qnMZ** [comment]
@HBTE sub KMcCxYwhvgw2Y5n6qnMZ@gmx.de

**Comment by KMcCxYwhvgw2Y5n6qnMZ** [comment]
@HBTE pub
An beide Karten
